name: Build

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    name: Build and Analyze with SonarQube
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false || github.event.action == 'ready_for_review'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.3.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Check SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        continue-on-error: true
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Continue Build
        run: echo "SonarQube check completed — continuing even if Quality Gate failed."
